### ISSUE TITLE
.ods mimetype is not correct

### ISSUE THREAD

**Issue by Romex91** [samuelneff/MimeTypeMap#8] opened 2015-03-27 12:12 UTC
It should be  "application/vnd.oasis.opendocument.spreadsheet"

**Comment by samuelneff** [comment] 2015-04-22 15:04
It's not really wrong. The problem is OpenOffice used `.ods` for their files when `.ods` was already in use for another purpose. There are two correct mappings for `.ods.`

See

https://support.microsoft.com/en-us/kb/936496

and

http://www.openoffice.org/framework/documentation/mimetypes/mimetypes.html

I am going to make the requested change though. Since now `.ods` will more commonly be associated with OpenOffice as opposed to an OLE object.

Thanks!

Sam

**Comment by samuelneff** [comment] 2015-04-22 15:21
Changes committed, plus I added other missing OpenOffice mime types. Thanks for letting me know.

**Closed by samuelneff** 2015-04-22 15:21 UTC
